# values.yaml

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

env:
  USERNAME: admin
  PASSWORD: supersecret123

service:
  type: ClusterIP
  port: 80

resources: {}
